FROM python:3.10-slim

# Upgrade pip
RUN pip install --upgrade pip

WORKDIR /app

# Copy and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -U pip setuptools \
    && pip install --no-cache-dir -r requirements.txt

# Install system dependencies
RUN apt-get update -y \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        tzdata ca-certificates bzip2 curl wget libc-dev libxt6 \
        libxrender1 libx11-xcb1 libdbus-glib-1-2 libgtk-3-0 \
        $(apt-cache depends firefox-esr | awk '/Depends:/{print $2}') \
    && update-ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

# Install the correct version of geckodriver
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz && \
    tar -zxf geckodriver-v0.33.0-linux64.tar.gz -C /usr/local/bin && \
    chmod +x /usr/local/bin/geckodriver && \
    rm geckodriver-v0.33.0-linux64.tar.gz

# Install Firefox
RUN FIREFOX_SETUP=firefox-setup.tar.bz2 && \
    wget -O $FIREFOX_SETUP "https://download.mozilla.org/?product=firefox-112.0.1&os=linux64" && \
    tar xjf $FIREFOX_SETUP -C /opt/ && \
    ln -s /opt/firefox/firefox /usr/bin/firefox && \
    rm $FIREFOX_SETUP

# Copy environment variables
COPY os.env /app/os.env
# Source environment variables
RUN export $(cat os.env | xargs)

# Copy application code
COPY . /app

# Command to run your application
CMD ["python3", "scraper.py"]